version: '3.7'

services:
  bot:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - '2399:2399'
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    command: redis-server --requirepass uMRn30MfGfuNzYrojcHaD
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 10s
      timeout: 5s
    ports:
      - '6379:6379'
    expose:
      - 6379

#   pg_backup:
#     image: eeshugerman/postgres-backup-s3:13
#     networks:
#       - postgres
#     env_file:
#       - ./.env.pgbackup

# networks:
#   postgres:
#     external: true
#     name: reaction-roles_default

volumes:
  redis_data:
